---
title: "Homework2"
author: "Josh Graybiel"
date: "May 17, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
Reading the file in
```{r}
gaz_raw<- read.delim("CA_Features_20180401.txt",
                   sep = "|", quote = "\"", dec = ".", fill = TRUE, comment.char = "", na.strings = "NA")
as_tibble(gaz_raw)
```
Tiddying up the file and organizing the headers.

```{r}
colnames(gaz_raw)
newgaz_raw<- select(gaz_raw, FEATURE_ID: STATE_ALPHA, COUNTY_NAME, ends_with("DEC"), ends_with("M"), starts_with("map"), starts_with("DATE"))
colnames(newgaz_raw)<- c("feature ID", 
                     "feature name", 
                     "feature class", 
                     "state alpha", 
                     "county name", 
                     "primary latitude (decimal)", 
                     "primary longitude (decimal)", 
                     "source latitude (decimal)", 
                     "source longitude (decimal)", 
                     "elevation in meters", 
                     "map name", 
                     "date created",
                     "date edited")
as.tibble(newgaz_raw)
tibble<- as.tibble(newgaz_raw)
write_csv(tibble, "tibble.csv")
gaz_edit<- read_csv("tibble.csv")
gaz_edit
gaz_edit %>% 
  drop_na("primary latitude (decimal)", "primary longitude (decimal)")
gaz_edit %>% 
  filter(`state alpha`== "CA")
gaz_edit
```

Creating a Database for the gaz_edit file
```{r}
library(dplyr)
library(DBI)
library(RSQLite)

con <- DBI::dbConnect(RSQLite::SQLite(), path = ":memory")

copy_to(con, gaz_edit, "gaz_edit",
        temporary = FALSE)
gaz_db <- tbl(con, "gaz_edit")
gazdf<- as.data.frame(gaz_edit)
class(gaz_edit)
```

Analyzing the Data
```{r}
#Question 1
names<- dbGetQuery(con, "select(`feature name`), COUNT(`feature name`) AS count FROM gaz_edit GROUP BY (`feature name`) ORDER BY count DESC LIMIT 10;")

names

#Question 2
names2<- dbGetQuery(con, "select(`feature class`), COUNT(`feature class`) AS count FROM gaz_edit GROUP BY (`feature class`) ORDER BY count ASC LIMIT 10;")

names2

#Question 3
justcoordinatesdf<- select(gaz_edit, "county name" , "primarylat","primarylong") %>% group_by(`county name`) 

justcoordinatesfilterdf<-filter(justcoordinates, `primarylat` !=0 , `primarylong` !=0)

coordinateanalysis<- summarize(justcoordinatesfilterdf, 
                        maxlat=max(`primarylat`),
                        minlat=min(`primarylat`), 
                        maxlong=max(`primarylong`),
                        minlong=min(`primarylong`))

findingmiddle<-coordinateanalysis %>% 
  mutate(centerlat=maxlat+minlat/2, 
         centerlong=maxlong+minlong/2
  )

findingmiddle

findingmiddledf1<- as.data.frame(findingmiddle)


test<- copy_to(con, findingmiddledf1, 
        temporary = FALSE)

q3<- dbGetQuery(con,'
  SELECT "county name" , `centerlat` , `centerlong` 
  FROM `findingmiddledf1` 
  GROUP BY ("county name")
')

#Question 4
gazq4<- copy_to(con, gazdf, 
        temporary = FALSE)


q4df<- dbGetQuery(con," SELECT `county name`, `feature class`, 
       CASE 
        WHEN `feature class` IN ('Airport', 'Bridge', 'Building', 'Canal', 'Cemetery', 'Census', 'Church', 'Civil', 'Crossing', 'Dam', 'Harbor', 'Hospital', 'Locale', 'Military', 'Mine', 'Oilfield', 'Park', 'Pillar', 'Populated Place', 'Post Office', 'Reserve', 'Reservoir', 'School', 'Tower', 'Trail', 'Tunnel', 'Well')
         THEN 'manmade'
         ELSE 'natural'
      END AS 'category'
  FROM `gazdf`
  GROUP BY (`county name`)
")   

q4tbl<- copy_to(con, q4df,
                temporary = FALSE)
```
